# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Sun May 15 11:41:40 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(461, 415)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_Quit = QtGui.QPushButton(self.centralwidget)
        self.pushButton_Quit.setGeometry(QtCore.QRect(340, 340, 110, 32))
        self.pushButton_Quit.setObjectName("pushButton_Quit")
        self.groupBox_Input = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_Input.setGeometry(QtCore.QRect(10, 0, 441, 181))
        self.groupBox_Input.setObjectName("groupBox_Input")
        self.label = QtGui.QLabel(self.groupBox_Input)
        self.label.setGeometry(QtCore.QRect(120, 100, 41, 21))
        self.label.setObjectName("label")
        self.lineEdit_Input_McAddress = QtGui.QLineEdit(self.groupBox_Input)
        self.lineEdit_Input_McAddress.setGeometry(QtCore.QRect(180, 100, 111, 21))
        self.lineEdit_Input_McAddress.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_Input_McAddress.setObjectName("lineEdit_Input_McAddress")
        self.radioButton_Input_Mc = QtGui.QRadioButton(self.groupBox_Input)
        self.radioButton_Input_Mc.setEnabled(True)
        self.radioButton_Input_Mc.setGeometry(QtCore.QRect(10, 100, 111, 21))
        self.radioButton_Input_Mc.setCheckable(False)
        self.radioButton_Input_Mc.setChecked(False)
        self.radioButton_Input_Mc.setObjectName("radioButton_Input_Mc")
        self.radioButton_Input_File = QtGui.QRadioButton(self.groupBox_Input)
        self.radioButton_Input_File.setGeometry(QtCore.QRect(10, 140, 101, 21))
        self.radioButton_Input_File.setCheckable(False)
        self.radioButton_Input_File.setObjectName("radioButton_Input_File")
        self.radioButton_Input_Uc = QtGui.QRadioButton(self.groupBox_Input)
        self.radioButton_Input_Uc.setGeometry(QtCore.QRect(10, 120, 101, 21))
        self.radioButton_Input_Uc.setCheckable(False)
        self.radioButton_Input_Uc.setObjectName("radioButton_Input_Uc")
        self.lineEdit_Input_File = QtGui.QLineEdit(self.groupBox_Input)
        self.lineEdit_Input_File.setGeometry(QtCore.QRect(120, 140, 281, 21))
        self.lineEdit_Input_File.setReadOnly(True)
        self.lineEdit_Input_File.setObjectName("lineEdit_Input_File")
        self.pushButton_Input_File = QtGui.QPushButton(self.groupBox_Input)
        self.pushButton_Input_File.setGeometry(QtCore.QRect(400, 140, 31, 21))
        self.pushButton_Input_File.setObjectName("pushButton_Input_File")
        self.lineEdit_Input_McPort = QtGui.QLineEdit(self.groupBox_Input)
        self.lineEdit_Input_McPort.setEnabled(True)
        self.lineEdit_Input_McPort.setGeometry(QtCore.QRect(350, 100, 81, 21))
        self.lineEdit_Input_McPort.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_Input_McPort.setObjectName("lineEdit_Input_McPort")
        self.lineEdit_Input_UcPort = QtGui.QLineEdit(self.groupBox_Input)
        self.lineEdit_Input_UcPort.setGeometry(QtCore.QRect(350, 120, 81, 21))
        self.lineEdit_Input_UcPort.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_Input_UcPort.setObjectName("lineEdit_Input_UcPort")
        self.label_5 = QtGui.QLabel(self.groupBox_Input)
        self.label_5.setGeometry(QtCore.QRect(310, 100, 31, 21))
        self.label_5.setObjectName("label_5")
        self.label_9 = QtGui.QLabel(self.groupBox_Input)
        self.label_9.setGeometry(QtCore.QRect(310, 120, 31, 21))
        self.label_9.setObjectName("label_9")
        self.radioButton_Input_Tcp = QtGui.QRadioButton(self.groupBox_Input)
        self.radioButton_Input_Tcp.setEnabled(True)
        self.radioButton_Input_Tcp.setGeometry(QtCore.QRect(10, 50, 101, 21))
        self.radioButton_Input_Tcp.setChecked(True)
        self.radioButton_Input_Tcp.setObjectName("radioButton_Input_Tcp")
        self.label_2 = QtGui.QLabel(self.groupBox_Input)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 81, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(self.groupBox_Input)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 56, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtGui.QLabel(self.groupBox_Input)
        self.label_4.setGeometry(QtCore.QRect(120, 50, 51, 21))
        self.label_4.setObjectName("label_4")
        self.lineEdit_Input_TcpPort = QtGui.QLineEdit(self.groupBox_Input)
        self.lineEdit_Input_TcpPort.setEnabled(True)
        self.lineEdit_Input_TcpPort.setGeometry(QtCore.QRect(350, 50, 81, 21))
        self.lineEdit_Input_TcpPort.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_Input_TcpPort.setObjectName("lineEdit_Input_TcpPort")
        self.lineEdit_Input_TcpAddress = QtGui.QLineEdit(self.groupBox_Input)
        self.lineEdit_Input_TcpAddress.setGeometry(QtCore.QRect(180, 50, 111, 21))
        self.lineEdit_Input_TcpAddress.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_Input_TcpAddress.setObjectName("lineEdit_Input_TcpAddress")
        self.label_7 = QtGui.QLabel(self.groupBox_Input)
        self.label_7.setGeometry(QtCore.QRect(310, 50, 31, 21))
        self.label_7.setObjectName("label_7")
        self.lineEdit_Input_UcAddress = QtGui.QLineEdit(self.groupBox_Input)
        self.lineEdit_Input_UcAddress.setGeometry(QtCore.QRect(180, 120, 111, 21))
        self.lineEdit_Input_UcAddress.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_Input_UcAddress.setObjectName("lineEdit_Input_UcAddress")
        self.label_14 = QtGui.QLabel(self.groupBox_Input)
        self.label_14.setGeometry(QtCore.QRect(120, 120, 51, 21))
        self.label_14.setObjectName("label_14")
        self.pushButton_Draw = QtGui.QPushButton(self.centralwidget)
        self.pushButton_Draw.setGeometry(QtCore.QRect(230, 340, 110, 32))
        self.pushButton_Draw.setObjectName("pushButton_Draw")
        self.groupBox_Input_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_Input_2.setGeometry(QtCore.QRect(10, 180, 441, 141))
        self.groupBox_Input_2.setObjectName("groupBox_Input_2")
        self.label_6 = QtGui.QLabel(self.groupBox_Input_2)
        self.label_6.setGeometry(QtCore.QRect(120, 30, 61, 21))
        self.label_6.setObjectName("label_6")
        self.lineEdit_Output_Udp1Address = QtGui.QLineEdit(self.groupBox_Input_2)
        self.lineEdit_Output_Udp1Address.setGeometry(QtCore.QRect(180, 30, 111, 21))
        self.lineEdit_Output_Udp1Address.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_Output_Udp1Address.setObjectName("lineEdit_Output_Udp1Address")
        self.checkBox_Output_Udp1 = QtGui.QCheckBox(self.groupBox_Input_2)
        self.checkBox_Output_Udp1.setGeometry(QtCore.QRect(10, 30, 85, 18))
        self.checkBox_Output_Udp1.setCheckable(False)
        self.checkBox_Output_Udp1.setObjectName("checkBox_Output_Udp1")
        self.checkBox_Output_Udp2 = QtGui.QCheckBox(self.groupBox_Input_2)
        self.checkBox_Output_Udp2.setGeometry(QtCore.QRect(10, 50, 85, 18))
        self.checkBox_Output_Udp2.setCheckable(False)
        self.checkBox_Output_Udp2.setObjectName("checkBox_Output_Udp2")
        self.checkBox_Output_File = QtGui.QCheckBox(self.groupBox_Input_2)
        self.checkBox_Output_File.setGeometry(QtCore.QRect(10, 90, 85, 18))
        self.checkBox_Output_File.setCheckable(False)
        self.checkBox_Output_File.setObjectName("checkBox_Output_File")
        self.checkBox_Output_Mapview = QtGui.QCheckBox(self.groupBox_Input_2)
        self.checkBox_Output_Mapview.setGeometry(QtCore.QRect(10, 110, 85, 18))
        self.checkBox_Output_Mapview.setObjectName("checkBox_Output_Mapview")
        self.label_8 = QtGui.QLabel(self.groupBox_Input_2)
        self.label_8.setGeometry(QtCore.QRect(120, 50, 61, 21))
        self.label_8.setObjectName("label_8")
        self.lineEdit_Output_Udp2Address = QtGui.QLineEdit(self.groupBox_Input_2)
        self.lineEdit_Output_Udp2Address.setGeometry(QtCore.QRect(180, 50, 111, 21))
        self.lineEdit_Output_Udp2Address.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_Output_Udp2Address.setObjectName("lineEdit_Output_Udp2Address")
        self.lineEdit_Output_File = QtGui.QLineEdit(self.groupBox_Input_2)
        self.lineEdit_Output_File.setGeometry(QtCore.QRect(130, 90, 271, 21))
        self.lineEdit_Output_File.setReadOnly(True)
        self.lineEdit_Output_File.setObjectName("lineEdit_Output_File")
        self.pushButton_Output_File = QtGui.QPushButton(self.groupBox_Input_2)
        self.pushButton_Output_File.setGeometry(QtCore.QRect(400, 90, 31, 21))
        self.pushButton_Output_File.setObjectName("pushButton_Output_File")
        self.label_10 = QtGui.QLabel(self.groupBox_Input_2)
        self.label_10.setGeometry(QtCore.QRect(310, 30, 31, 21))
        self.label_10.setObjectName("label_10")
        self.lineEdit_Output_Udp1Port = QtGui.QLineEdit(self.groupBox_Input_2)
        self.lineEdit_Output_Udp1Port.setEnabled(True)
        self.lineEdit_Output_Udp1Port.setGeometry(QtCore.QRect(350, 30, 81, 21))
        self.lineEdit_Output_Udp1Port.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_Output_Udp1Port.setObjectName("lineEdit_Output_Udp1Port")
        self.label_11 = QtGui.QLabel(self.groupBox_Input_2)
        self.label_11.setGeometry(QtCore.QRect(310, 50, 31, 21))
        self.label_11.setObjectName("label_11")
        self.lineEdit_Output_Udp2Port = QtGui.QLineEdit(self.groupBox_Input_2)
        self.lineEdit_Output_Udp2Port.setGeometry(QtCore.QRect(350, 50, 81, 21))
        self.lineEdit_Output_Udp2Port.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_Output_Udp2Port.setObjectName("lineEdit_Output_Udp2Port")
        self.lineEdit_Output_Udp3Port = QtGui.QLineEdit(self.groupBox_Input_2)
        self.lineEdit_Output_Udp3Port.setGeometry(QtCore.QRect(350, 70, 81, 21))
        self.lineEdit_Output_Udp3Port.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_Output_Udp3Port.setObjectName("lineEdit_Output_Udp3Port")
        self.checkBox_Output_Udp3 = QtGui.QCheckBox(self.groupBox_Input_2)
        self.checkBox_Output_Udp3.setGeometry(QtCore.QRect(10, 70, 85, 18))
        self.checkBox_Output_Udp3.setCheckable(False)
        self.checkBox_Output_Udp3.setObjectName("checkBox_Output_Udp3")
        self.label_12 = QtGui.QLabel(self.groupBox_Input_2)
        self.label_12.setGeometry(QtCore.QRect(310, 70, 31, 21))
        self.label_12.setObjectName("label_12")
        self.lineEdit_Output_Udp3Address = QtGui.QLineEdit(self.groupBox_Input_2)
        self.lineEdit_Output_Udp3Address.setGeometry(QtCore.QRect(180, 70, 111, 21))
        self.lineEdit_Output_Udp3Address.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_Output_Udp3Address.setObjectName("lineEdit_Output_Udp3Address")
        self.label_13 = QtGui.QLabel(self.groupBox_Input_2)
        self.label_13.setGeometry(QtCore.QRect(120, 70, 61, 21))
        self.label_13.setObjectName("label_13")
        self.pushButton_Start = QtGui.QPushButton(self.centralwidget)
        self.pushButton_Start.setGeometry(QtCore.QRect(10, 340, 110, 32))
        self.pushButton_Start.setObjectName("pushButton_Start")
        self.pushButton_Stop = QtGui.QPushButton(self.centralwidget)
        self.pushButton_Stop.setGeometry(QtCore.QRect(120, 340, 110, 32))
        self.pushButton_Stop.setObjectName("pushButton_Stop")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 461, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Asterix Extravaganza", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Quit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_Input.setTitle(QtGui.QApplication.translate("MainWindow", "Input", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Group:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_Input_McAddress.setInputMask(QtGui.QApplication.translate("MainWindow", "000.000.000.000; ", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_Input_Mc.setText(QtGui.QApplication.translate("MainWindow", "UDP/Multicast", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_Input_File.setText(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_Input_Uc.setText(QtGui.QApplication.translate("MainWindow", "UDP/Unicast", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Input_File.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_Input_McPort.setInputMask(QtGui.QApplication.translate("MainWindow", "00000; ", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_Input_UcPort.setInputMask(QtGui.QApplication.translate("MainWindow", "00000; ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Port:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Port:", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_Input_Tcp.setText(QtGui.QApplication.translate("MainWindow", "TCP/Unicast", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "ADS-B Raw", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Asterix", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Address:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_Input_TcpPort.setInputMask(QtGui.QApplication.translate("MainWindow", "00000; ", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_Input_TcpPort.setText(QtGui.QApplication.translate("MainWindow", "30334", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_Input_TcpAddress.setInputMask(QtGui.QApplication.translate("MainWindow", "000.000.000.000; ", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_Input_TcpAddress.setText(QtGui.QApplication.translate("MainWindow", "90.230.225.244", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Port:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_Input_UcAddress.setInputMask(QtGui.QApplication.translate("MainWindow", "000.000.000.000; ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Address:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Draw.setText(QtGui.QApplication.translate("MainWindow", "Draw Map", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_Input_2.setTitle(QtGui.QApplication.translate("MainWindow", "Output", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Address:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_Output_Udp1Address.setInputMask(QtGui.QApplication.translate("MainWindow", "000.000.000.000; ", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_Output_Udp1.setText(QtGui.QApplication.translate("MainWindow", "UDP", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_Output_Udp2.setText(QtGui.QApplication.translate("MainWindow", "UDP", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_Output_File.setText(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_Output_Mapview.setText(QtGui.QApplication.translate("MainWindow", "Mapview", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Address:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_Output_Udp2Address.setInputMask(QtGui.QApplication.translate("MainWindow", "000.000.000.000; ", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Output_File.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Port:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_Output_Udp1Port.setInputMask(QtGui.QApplication.translate("MainWindow", "00000; ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Port:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_Output_Udp2Port.setInputMask(QtGui.QApplication.translate("MainWindow", "00000; ", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_Output_Udp3Port.setInputMask(QtGui.QApplication.translate("MainWindow", "00000; ", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_Output_Udp3.setText(QtGui.QApplication.translate("MainWindow", "UDP", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Port:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_Output_Udp3Address.setInputMask(QtGui.QApplication.translate("MainWindow", "000.000.000.000; ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Address:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Start.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Stop.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))

